### ISSUE TITLE
Where the cue are?

### ISSUE THREAD

**Issue by maoyang** [kkdai/LineBotPetNeedMe#2]
你的bot我加入好友後會給我一個private message跟我說明如何使用 ? 這算是一個cue, 讓我知道下一步要做什麼?

**Comment by kkdai** [comment]
Current Msg: "您好，感謝你加入成為好友一起幫助流浪動物找到新的家．輸入任何文字後，會隨機得到一個流浪動物，你可以不斷重複輸入文字然後查看目前所有的流浪動物．"
